# DAV 5400 Module 3 Assignment


## Introduction:

In this assingment we basically use the functionality provided by Python’s NumPy package.



For this task, we need to import the numpy library by using the import keyword and numpy as np.

### Task 1:
1. (5 Points) Write a Python/NumPy code block that finds the distinct array items that exist in either array a or array b
but which do not appear within both arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
For example, if a 2 is found in both array a and array b, your output should not include a 2. Furthermore, the content of
the output should be comprised solely of unique data values.

### Solution:

#### 1.  Importing numpy library:
- For this task, we need to import the numpy library by using the import keyword and numpy as np.
- This bascially helps for us to use all the inbuilt numpy functions.
#### 2. arrays a and b:
- These are the predefined arrays given to us and for this task we are going to convert the arrrays into sets.
#### 3. set a and b:
- To convert the arrays into set we used set fucntion.
#### 4. '^' XOR operation:
- To find the unique values i used the XOR operation for this which will basically checks the two sets and gives us the distinct values.



In [57]:
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
print(a,b)

set_a = set(a)#converting arrays into sets
set_b = set(b)

unidue_data_values = np.array(list(set_a ^ set_b))#using XOR operation for comparing sets

print(unidue_data_values)

[1 2 3 2 3 4 3 4 5 6] [ 7  2 10  2  7  4  9  4  9  8]
[ 1  3  5  6  7  8  9 10]


## solution method 2:
- Here i used the setdiff1d inbuilt fucntion along with the union and intersect1d which will gather all the union of two sets and intersection.
- In union all the elements will be subtracted with the common intersecting elements then we will get unique elements.

In [58]:
unidue_data_values= np.setdiff1d(np.union1d(a, b), np.intersect1d(a, b))

print(unidue_data_values)


[ 1  3  5  6  7  8  9 10]


### Task 2:

2. (5 Points) Create the following 4x5 array using knowledge you have of Python’s / NumPy’s sequencing functionality
so that you do not need to explicitly key in every integer value.
1 5 9 13 17
2 6 10 14 18
3 7 11 15 19
4 8 12 16 20

### Solution:

#### 1.  arr1:
- For this task, we are storing the array into this newly created arr1 variable.
#### 2. arange():
- It is a function which will help us create an array with regularly spaced values within a specified range.
#### 3. reshape():
- This function changes the shape of an array without changing its data. It returns a new array with the same data but a different shape

By using these two functions we can get our desired output.

In [60]:
arr1=np.arange(1,21).reshape(4,5).T 
arr1

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

### Task 3:
3. (5 Points) You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5, 3, 4])
Write a Python/Numpy code block that adds to array a any items that are present in array b but not already present
within array a.

### Solution:

#### 1.Unique_b: 
- This is the variable i have created to store the unique values in 'b' array which is not present in the 'a' array.
#### 2. setdiff1d(b,a):
- to get unique value

In [59]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5, 3, 4])

unique_b = np.setdiff1d(b, a)


a = np.concatenate((a, unique_b))

a

array([12,  5,  7, 15,  3,  1,  8,  4,  6, 11, 14, 19])

In [62]:
print(arr1)

for x in np.nditer(arr1):
    print(x)

[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


### Task 5:
5. (8 Points) For this problem you will load a small data set to your online GitHub repository and then read it into a
NumPy 2D array. You will then use the content that NumPy array to answer a series of analytical questions.

In [64]:
import pandas
import numpy as np
# suppress scientific notation
np.set_printoptions(suppress = True)
# read the data file from GitHub and convert to a NumPy ndarray object
# be sure to replace the ‘link_to_raw_copy of data file in your Github Repository’ placeholder shown below
# with a link to the “raw” version of the file you pushed to your online GitHub repository
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/Nikkat-Afrin/DAV-5400/master/M3_Data.csv').to_numpy()
# verify you have an ndarray object
type(nyc_water)

numpy.ndarray

In [65]:
nyc_water

array([[   1979. , 7102100. ,    1512. ,     213. ],
       [   1980. , 7071639. ,    1506. ,     213. ],
       [   1981. , 7089241. ,    1309. ,     185. ],
       [   1982. , 7109105. ,    1382. ,     194. ],
       [   1983. , 7181224. ,    1424. ,     198. ],
       [   1984. , 7234514. ,    1465. ,     203. ],
       [   1985. , 7274054. ,    1326. ,     182. ],
       [   1986. , 7319246. ,    1351. ,     185. ],
       [   1987. , 7342476. ,    1447. ,     197. ],
       [   1988. , 7353719. ,    1484. ,     202. ],
       [   1989. , 7344175. ,    1402. ,     191. ],
       [   1990. , 7335650. ,    1424. ,     194. ],
       [   1991. , 7374501. ,    1469. ,     199. ],
       [   1992. , 7428944. ,    1369. ,     184. ],
       [   1993. , 7506166. ,    1368.5,     182. ],
       [   1994. , 7570458. ,    1357.7,     179. ],
       [   1995. , 7633040. ,    1325.7,     174. ],
       [   1996. , 7697812. ,    1297.9,     169. ],
       [   1997. , 7773443. ,    1205.5,     1

In [66]:
# Extract the per capita column
per_capita_column = nyc_water[:, 3]

# Find the index of the maximum per capita value
max_per_capita_index = np.argmax(per_capita_column)

# Get the year with the maximum per capita
year_with_max_per_capita = nyc_water[max_per_capita_index, 0]

print("Year with the maximum per capita daily water consumption:", year_with_max_per_capita)

Year with the maximum per capita daily water consumption: 1979.0


In [67]:
# Calculate annual change in population and add a new column
population_column = nyc_water[:, 1]
annual_change_column = np.append([np.nan], np.diff(population_column))

# Add the new column to the array
nyc_water = np.column_stack((nyc_water, annual_change_column))

print("Updated NYC Water array with the annual change in population:")
print(nyc_water)

Updated NYC Water array with the annual change in population:
[[   1979.  7102100.     1512.      213.        nan]
 [   1980.  7071639.     1506.      213.   -30461. ]
 [   1981.  7089241.     1309.      185.    17602. ]
 [   1982.  7109105.     1382.      194.    19864. ]
 [   1983.  7181224.     1424.      198.    72119. ]
 [   1984.  7234514.     1465.      203.    53290. ]
 [   1985.  7274054.     1326.      182.    39540. ]
 [   1986.  7319246.     1351.      185.    45192. ]
 [   1987.  7342476.     1447.      197.    23230. ]
 [   1988.  7353719.     1484.      202.    11243. ]
 [   1989.  7344175.     1402.      191.    -9544. ]
 [   1990.  7335650.     1424.      194.    -8525. ]
 [   1991.  7374501.     1469.      199.    38851. ]
 [   1992.  7428944.     1369.      184.    54443. ]
 [   1993.  7506166.     1368.5     182.    77222. ]
 [   1994.  7570458.     1357.7     179.    64292. ]
 [   1995.  7633040.     1325.7     174.    62582. ]
 [   1996.  7697812.     1297.9     1

In [70]:
# Extract the population column
population_column = nyc_water[:, 1]

# Calculate median and variance
median_population = np.median(population_column)
variance_population = np.var(population_column)

print("Median population of the city:", median_population)
print("Variance of the population of the city:", variance_population)

Median population of the city: 7947660.0
Variance of the population of the city: 214014109798.73172


In [71]:
# Extract the annual change column
annual_change_column = nyc_water[:, -1]

# Calculate the average annual change, ignoring 'N/A' values
average_annual_change = np.nanmean(annual_change_column)

print("Average annual change in the population of the city:", average_annual_change)

Average annual change in the population of the city: 30867.925
